WR_SessionExport = {
  _prefix = "session",
  exportedBy = "Leftêr-Blackrock",
  formatVersion = 1,
  addonVersion = "2.0.0",
  characters = {
    {
      name = "Zaubermütze",
      characterType = "unlinked",
      characterId = "Zaubermütze-Blackrock",
      realm = "Blackrock",
    },
    {
      name = "Akopalüzenao",
      characterType = "unlinked",
      characterId = "Akopalüzenao-Blackrock",
      realm = "Blackrock",
    },
    {
      name = "Arzuria",
      characterType = "unlinked",
      characterId = "Arzuria-Blackrock",
      realm = "Blackrock",
    },
    {
      name = "Sonnez",
      characterType = "unlinked",
      characterId = "Sonnez-Blackrock",
      realm = "Blackrock",
    },
    {
      name = "Globusnuss",
      characterType = "unlinked",
      characterId = "Globusnuss-Blackrock",
      realm = "Blackrock",
    },
    {
      name = "Leftêr",
      characterType = "unlinked",
      characterId = "Leftêr-Blackrock",
      realm = "Blackrock",
    },
    {
      name = "Cevapchiji",
      characterType = "unlinked",
      characterId = "Cevapchiji-Blackrock",
      realm = "Blackrock",
    },
    {
      name = "Mønkéy",
      characterType = "unlinked",
      characterId = "Mønkéy-Blackrock",
      realm = "Blackrock",
    },
  },
  sessions = {
    {
      participants = {
        ["Zaubermütze-Blackrock"] = true,
        ["Akopalüzenao-Blackrock"] = true,
        ["Arzuria-Blackrock"] = true,
        ["Sonnez-Blackrock"] = true,
        ["Globusnuss-Blackrock"] = true,
        ["Leftêr-Blackrock"] = true,
        ["Cevapchiji-Blackrock"] = true,
        ["Mønkéy-Blackrock"] = true,
      },
      hostCharacter = "Akopalüzenao-Blackrock",
      endTime = 1779045535,
      gameType = "simpleDice",
      exportedAt = 1779050058,
      rounds = {
        {
          roundNumber = 1,
          rolls = {
            ["Zaubermütze-Blackrock"] = {
              timestamp = 1779045437,
              roll = 12178,
              maxRoll = 25000,
            },
            ["Arzuria-Blackrock"] = {
              timestamp = 1779045441,
              roll = 10030,
              maxRoll = 25000,
            },
            ["Sonnez-Blackrock"] = {
              timestamp = 1779045430,
              roll = 3857,
              maxRoll = 25000,
            },
            ["Leftêr-Blackrock"] = {
              timestamp = 1779045430,
              roll = 7479,
              maxRoll = 25000,
            },
            ["Mønkéy-Blackrock"] = {
              timestamp = 1779045431,
              roll = 13351,
              maxRoll = 25000,
            },
          },
          signedUp = {
            ["Zaubermütze-Blackrock"] = true,
            ["Arzuria-Blackrock"] = true,
            ["Sonnez-Blackrock"] = true,
            ["Leftêr-Blackrock"] = true,
            ["Mønkéy-Blackrock"] = true,
          },
          endTime = 1779045441,
          startTime = 1779045410,
          status = "completed",
          results = {
            loser = "Sonnez-Blackrock",
            lowestRoll = 3857,
            winner = "Mønkéy-Blackrock",
            highestRoll = 13351,
            payoutAmount = 9494,
          },
        },
        {
          roundNumber = 2,
          rolls = {
            ["Zaubermütze-Blackrock"] = {
              timestamp = 1779045472,
              roll = 21522,
              maxRoll = 25000,
            },
            ["Akopalüzenao-Blackrock"] = {
              timestamp = 1779045472,
              roll = 24788,
              maxRoll = 25000,
            },
            ["Arzuria-Blackrock"] = {
              timestamp = 1779045477,
              roll = 5773,
              maxRoll = 25000,
            },
            ["Mønkéy-Blackrock"] = {
              timestamp = 1779045474,
              roll = 23778,
              maxRoll = 25000,
            },
            ["Globusnuss-Blackrock"] = {
              timestamp = 1779045471,
              roll = 5282,
              maxRoll = 25000,
            },
            ["Leftêr-Blackrock"] = {
              timestamp = 1779045472,
              roll = 10373,
              maxRoll = 25000,
            },
            ["Sonnez-Blackrock"] = {
              timestamp = 1779045481,
              roll = 782,
              maxRoll = 25000,
            },
            ["Cevapchiji-Blackrock"] = {
              timestamp = 1779045473,
              roll = 18797,
              maxRoll = 25000,
            },
          },
          signedUp = {
            ["Zaubermütze-Blackrock"] = true,
            ["Akopalüzenao-Blackrock"] = true,
            ["Arzuria-Blackrock"] = true,
            ["Sonnez-Blackrock"] = true,
            ["Globusnuss-Blackrock"] = true,
            ["Leftêr-Blackrock"] = true,
            ["Cevapchiji-Blackrock"] = true,
            ["Mønkéy-Blackrock"] = true,
          },
          endTime = 1779045481,
          startTime = 1779045447,
          status = "completed",
          results = {
            loser = "Sonnez-Blackrock",
            lowestRoll = 782,
            winner = "Akopalüzenao-Blackrock",
            highestRoll = 24788,
            payoutAmount = 24006,
          },
        },
        {
          roundNumber = 3,
          rolls = {
            ["Zaubermütze-Blackrock"] = {
              timestamp = 1779045523,
              roll = 17489,
              maxRoll = 25000,
            },
            ["Akopalüzenao-Blackrock"] = {
              timestamp = 1779045521,
              roll = 19108,
              maxRoll = 25000,
            },
            ["Arzuria-Blackrock"] = {
              timestamp = 1779045531,
              roll = 5703,
              maxRoll = 25000,
            },
            ["Sonnez-Blackrock"] = {
              timestamp = 1779045530,
              roll = 4031,
              maxRoll = 25000,
            },
            ["Cevapchiji-Blackrock"] = {
              timestamp = 1779045523,
              roll = 22342,
              maxRoll = 25000,
            },
            ["Leftêr-Blackrock"] = {
              timestamp = 1779045522,
              roll = 18180,
              maxRoll = 25000,
            },
            ["Globusnuss-Blackrock"] = {
              timestamp = 1779045524,
              roll = 7356,
              maxRoll = 25000,
            },
          },
          signedUp = {
            ["Zaubermütze-Blackrock"] = true,
            ["Akopalüzenao-Blackrock"] = true,
            ["Arzuria-Blackrock"] = true,
            ["Sonnez-Blackrock"] = true,
            ["Globusnuss-Blackrock"] = true,
            ["Leftêr-Blackrock"] = true,
            ["Cevapchiji-Blackrock"] = true,
          },
          endTime = 1779045531,
          startTime = 1779045491,
          status = "completed",
          results = {
            loser = "Sonnez-Blackrock",
            lowestRoll = 4031,
            winner = "Cevapchiji-Blackrock",
            highestRoll = 22342,
            payoutAmount = 18311,
          },
        },
      },
      channel = "RAID",
      status = "completed",
      startTime = 1779045408,
      sessionId = "1779045408_1",
      sessionStats = {
        leaderboard = {
          ["Cevapchiji-Blackrock"] = 18311,
          ["Akopalüzenao-Blackrock"] = 24006,
          ["Sonnez-Blackrock"] = -51811,
          ["Mønkéy-Blackrock"] = 9494,
        },
        totalRounds = 3,
        totalPayouts = 51811,
      },
    },
    {
      participants = {
        ["Zaubermütze-Blackrock"] = true,
        ["Akopalüzenao-Blackrock"] = true,
        ["Sonnez-Blackrock"] = true,
        ["Globusnuss-Blackrock"] = true,
        ["Leftêr-Blackrock"] = true,
        ["Mønkéy-Blackrock"] = true,
      },
      hostCharacter = "Akopalüzenao-Blackrock",
      endTime = 1779038968,
      gameType = "simpleDice",
      exportedAt = 1779050058,
      rounds = {
        {
          roundNumber = 1,
          rolls = {
            ["Zaubermütze-Blackrock"] = {
              timestamp = 1779038955,
              roll = 16041,
              maxRoll = 25000,
            },
            ["Akopalüzenao-Blackrock"] = {
              timestamp = 1779038955,
              roll = 14548,
              maxRoll = 25000,
            },
            ["Mønkéy-Blackrock"] = {
              timestamp = 1779038962,
              roll = 13741,
              maxRoll = 25000,
            },
            ["Globusnuss-Blackrock"] = {
              timestamp = 1779038958,
              roll = 20415,
              maxRoll = 25000,
            },
            ["Leftêr-Blackrock"] = {
              timestamp = 1779038956,
              roll = 5541,
              maxRoll = 25000,
            },
            ["Sonnez-Blackrock"] = {
              timestamp = 1779038965,
              roll = 20,
              maxRoll = 25000,
            },
          },
          signedUp = {
            ["Zaubermütze-Blackrock"] = true,
            ["Akopalüzenao-Blackrock"] = true,
            ["Sonnez-Blackrock"] = true,
            ["Globusnuss-Blackrock"] = true,
            ["Leftêr-Blackrock"] = true,
            ["Mønkéy-Blackrock"] = true,
          },
          endTime = 1779038965,
          startTime = 1779038945,
          status = "completed",
          results = {
            loser = "Sonnez-Blackrock",
            lowestRoll = 20,
            winner = "Globusnuss-Blackrock",
            highestRoll = 20415,
            payoutAmount = 20395,
          },
        },
      },
      channel = "RAID",
      status = "completed",
      startTime = 1779038943,
      sessionId = "1779038943_1",
      sessionStats = {
        leaderboard = {
          ["Globusnuss-Blackrock"] = 20395,
          ["Sonnez-Blackrock"] = -20395,
        },
        totalRounds = 1,
        totalPayouts = 20395,
      },
    },
    {
      participants = {
        ["Zaubermütze-Blackrock"] = true,
        ["Leftêr-Blackrock"] = true,
        ["Akopalüzenao-Blackrock"] = true,
        ["Sonnez-Blackrock"] = true,
      },
      hostCharacter = "Leftêr-Blackrock",
      sessionId = "1779044637_1",
      gameType = "simpleDice",
      exportedAt = 1779050058,
      rounds = {
        {
          roundNumber = 1,
          rolls = {
            ["Zaubermütze-Blackrock"] = {
              timestamp = 1779044710,
              roll = 13910,
              maxRoll = 25000,
            },
            ["Leftêr-Blackrock"] = {
              timestamp = 1779044709,
              roll = 3342,
              maxRoll = 25000,
            },
            ["Akopalüzenao-Blackrock"] = {
              timestamp = 1779044731,
              roll = 22734,
              maxRoll = 25000,
            },
            ["Sonnez-Blackrock"] = {
              timestamp = 1779044710,
              roll = 23213,
              maxRoll = 25000,
            },
          },
          signedUp = {
            ["Zaubermütze-Blackrock"] = true,
            ["Leftêr-Blackrock"] = true,
            ["Akopalüzenao-Blackrock"] = true,
            ["Sonnez-Blackrock"] = true,
          },
          endTime = 1779044731,
          startTime = 1779044639,
          status = "completed",
          results = {
            loser = "Leftêr-Blackrock",
            lowestRoll = 3342,
            winner = "Sonnez-Blackrock",
            payoutAmount = 19871,
            highestRoll = 23213,
          },
        },
      },
      channel = "RAID",
      status = "abandoned",
      startTime = 1779044637,
      endTime = 1779049912,
      sessionStats = {
        leaderboard = {
          ["Leftêr-Blackrock"] = -19871,
          ["Sonnez-Blackrock"] = 19871,
        },
        totalRounds = 1,
        totalPayouts = 19871,
      },
    },
    {
      participants = {
        ["Zaubermütze-Blackrock"] = true,
        ["Akopalüzenao-Blackrock"] = true,
        ["Arzuria-Blackrock"] = true,
        ["Mønkéy-Blackrock"] = true,
        ["Globusnuss-Blackrock"] = true,
        ["Leftêr-Blackrock"] = true,
        ["Sonnez-Blackrock"] = true,
      },
      hostCharacter = "Leftêr-Blackrock",
      sessionId = "1779037098_1",
      gameType = "simpleDice",
      exportedAt = 1779050058,
      rounds = {
        {
          roundNumber = 1,
          rolls = {
            ["Zaubermütze-Blackrock"] = {
              timestamp = 1779037187,
              roll = 9142,
              maxRoll = 25000,
            },
            ["Akopalüzenao-Blackrock"] = {
              timestamp = 1779037190,
              roll = 7686,
              maxRoll = 25000,
            },
            ["Mønkéy-Blackrock"] = {
              timestamp = 1779037209,
              roll = 17732,
              maxRoll = 25000,
            },
            ["Globusnuss-Blackrock"] = {
              timestamp = 1779037193,
              roll = 10894,
              maxRoll = 25000,
            },
            ["Leftêr-Blackrock"] = {
              timestamp = 1779037188,
              roll = 24751,
              maxRoll = 25000,
            },
            ["Sonnez-Blackrock"] = {
              timestamp = 1779037216,
              roll = 17723,
              maxRoll = 25000,
            },
          },
          signedUp = {
            ["Zaubermütze-Blackrock"] = true,
            ["Akopalüzenao-Blackrock"] = true,
            ["Mønkéy-Blackrock"] = true,
            ["Globusnuss-Blackrock"] = true,
            ["Leftêr-Blackrock"] = true,
            ["Sonnez-Blackrock"] = true,
          },
          endTime = 1779037216,
          startTime = 1779037102,
          status = "completed",
          results = {
            loser = "Akopalüzenao-Blackrock",
            lowestRoll = 7686,
            winner = "Leftêr-Blackrock",
            payoutAmount = 17065,
            highestRoll = 24751,
          },
        },
        {
          roundNumber = 2,
          rolls = {
            ["Zaubermütze-Blackrock"] = {
              timestamp = 1779037256,
              roll = 23468,
              maxRoll = 25000,
            },
            ["Akopalüzenao-Blackrock"] = {
              timestamp = 1779037256,
              roll = 24038,
              maxRoll = 25000,
            },
            ["Arzuria-Blackrock"] = {
              timestamp = 1779037260,
              roll = 16411,
              maxRoll = 25000,
            },
            ["Sonnez-Blackrock"] = {
              timestamp = 1779037260,
              roll = 17012,
              maxRoll = 25000,
            },
            ["Globusnuss-Blackrock"] = {
              timestamp = 1779037256,
              roll = 3292,
              maxRoll = 25000,
            },
            ["Leftêr-Blackrock"] = {
              timestamp = 1779037255,
              roll = 21148,
              maxRoll = 25000,
            },
            ["Mønkéy-Blackrock"] = {
              timestamp = 1779037260,
              roll = 16647,
              maxRoll = 25000,
            },
          },
          signedUp = {
            ["Zaubermütze-Blackrock"] = true,
            ["Akopalüzenao-Blackrock"] = true,
            ["Arzuria-Blackrock"] = true,
            ["Sonnez-Blackrock"] = true,
            ["Globusnuss-Blackrock"] = true,
            ["Leftêr-Blackrock"] = true,
            ["Mønkéy-Blackrock"] = true,
          },
          endTime = 1779037260,
          startTime = 1779037226,
          status = "completed",
          results = {
            loser = "Globusnuss-Blackrock",
            lowestRoll = 3292,
            winner = "Akopalüzenao-Blackrock",
            payoutAmount = 20746,
            highestRoll = 24038,
          },
        },
      },
      channel = "RAID",
      status = "completed",
      startTime = 1779037098,
      sessionStats = {
        leaderboard = {
          ["Globusnuss-Blackrock"] = -20746,
          ["Leftêr-Blackrock"] = 17065,
          ["Akopalüzenao-Blackrock"] = 3681,
        },
        totalRounds = 2,
        totalPayouts = 37811,
      },
      endTime = 1779037291,
    },
  },
  format = "WhateverRoyale-Export",
  schemaVersion = 3,
  exportedAt = 1779050320,
}
